### ISSUE TITLE
Question: Are you planning on supporting MacOS targets?

### ISSUE THREAD

**Issue by lechuckcaptain** [EmergeTools/SnapshotPreviews-iOS#191]
I guess the title is quite self-explanatory: at the moment the library doesn't support MacOS targets. Are you planning on supporting it in the future? 

Thanks!

**Comment by noahsmartin** [comment]
Hi @lechuckcaptain we do support macOS, you can see how this works by changing the DemoApp target to "My Mac" in Xcode. You can then use `Preview Gallery` in the demo app. You can also run `DemoAppSnapshotTest` on the My Mac target to generate snapshots on macOS. Let me know if you run into any issues with this!
